[package]
name = "light-bitcoin-wasm-test"
version = "0.1.0"
authors = ["The ChainX Authors"]
edition = "2018"
license = "GPL-3.0"

[features]
std = ["light-bitcoin/std"]

[dependencies]
wee_alloc = "0.4.5"
light-bitcoin = { path = "../", default-features = false }
